name: deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - run: touch .env
      - run: echo "${{ secrets.ENV_FILE }}" > .env
      - run: cat .env


      - name: Docker build & push to dev
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hospital .
          docker push ${{ secrets.DOCKER_USERNAME }}/hospital

      - name: Deploy to dev
        uses: appleboy/ssh-action@master
        id: deploy-dev
        with:
          host: ${{ secrets.HOST_DEV }} # GCP 퍼블릭 IPv4 DNS
          username: ${{ secrets.USERNAME }} # GCP NAME
          port: 22
          key: ${{ secrets.PRIVATE_KEY }}
          script: |

            if docker ps -a | grep -q hospital; then
              docker stop hospital
              docker rm hospital
              docker rmi ${{ secrets.DOCKER_USERNAME }}/hospital
            fi
            if docker images -a | grep -q ${{ secrets.DOCKER_USERNAME }}/hospital; then
              docker rmi -f ${{ secrets.DOCKER_USERNAME }}/hospital
            fi
            docker pull ${{ secrets.DOCKER_USERNAME }}/hospital
            docker run -d -p 4000:4000 --name hospital ${{ secrets.DOCKER_USERNAME }}/hospital
